apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expensee
  region: us-east-1

managedNodeGroups:
  - name: expensee
    instanceTypes:
      - "t3.small"
      - "t3.medium"
      - "t3.large"
      - "m5.large"
      - "m5a.large"
      - "c5.large"
      - "c6i.large"
      - "c7i-flex.large"
    desiredCapacity: 3
    spot: true